[package]
name = "chat-bubbles"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tera = { version = "1", default-features = false }

[dev-dependencies]
usvg = "0.35"
open = "5.0"
